version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "gradlew"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "pom.xml"
    schedule:
      interval: "weekly"
