//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun acknowledgeRequest(block: com.google.pubsub.v1.AcknowledgeRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.AcknowledgeRequest =
  com.google.pubsub.v1.AcknowledgeRequestKt.Dsl._create(com.google.pubsub.v1.AcknowledgeRequest.newBuilder()).apply { block() }._build()
object AcknowledgeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.AcknowledgeRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.AcknowledgeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.AcknowledgeRequest = _builder.build()

    /**
     * <pre>
     * Required. The subscription whose message is being acknowledged.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var subscription: kotlin.String
      @JvmName("getSubscription")
      get() = _builder.getSubscription()
      @JvmName("setSubscription")
      set(value) {
        _builder.setSubscription(value)
      }
    /**
     * <pre>
     * Required. The subscription whose message is being acknowledged.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearSubscription() {
      _builder.clearSubscription()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class AckIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Required. The acknowledgment ID for the messages being acknowledged that
     * was returned by the Pub/Sub system in the `Pull` response. Must not be
     * empty.
     * </pre>
     *
     * <code>repeated string ack_ids = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return A list containing the ackIds.
     */
    val ackIds: com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAckIdsList()
      )
    /**
     * <pre>
     * Required. The acknowledgment ID for the messages being acknowledged that
     * was returned by the Pub/Sub system in the `Pull` response. Must not be
     * empty.
     * </pre>
     *
     * <code>repeated string ack_ids = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAckIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.add(value: kotlin.String) {
      _builder.addAckIds(value)
    }
    /**
     * <pre>
     * Required. The acknowledgment ID for the messages being acknowledged that
     * was returned by the Pub/Sub system in the `Pull` response. Must not be
     * empty.
     * </pre>
     *
     * <code>repeated string ack_ids = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAckIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.plusAssign(value: kotlin.String) {
      _builder.addAckIds(value)
    }
    /**
     * <pre>
     * Required. The acknowledgment ID for the messages being acknowledged that
     * was returned by the Pub/Sub system in the `Pull` response. Must not be
     * empty.
     * </pre>
     *
     * <code>repeated string ack_ids = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param values The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAckIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAckIds(values)
    }
    /**
     * <pre>
     * Required. The acknowledgment ID for the messages being acknowledged that
     * was returned by the Pub/Sub system in the `Pull` response. Must not be
     * empty.
     * </pre>
     *
     * <code>repeated string ack_ids = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param values The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAckIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAckIds(values)
    }
    /**
     * <pre>
     * Required. The acknowledgment ID for the messages being acknowledged that
     * was returned by the Pub/Sub system in the `Pull` response. Must not be
     * empty.
     * </pre>
     *
     * <code>repeated string ack_ids = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param index The index to set the value at.
     * @param value The ackIds to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAckIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setAckIds(index, value)
    }/**
     * <pre>
     * Required. The acknowledgment ID for the messages being acknowledged that
     * was returned by the Pub/Sub system in the `Pull` response. Must not be
     * empty.
     * </pre>
     *
     * <code>repeated string ack_ids = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAckIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.clear() {
      _builder.clearAckIds()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.AcknowledgeRequest.copy(block: com.google.pubsub.v1.AcknowledgeRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.AcknowledgeRequest =
  com.google.pubsub.v1.AcknowledgeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
