//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun deleteTopicRequest(block: com.google.pubsub.v1.DeleteTopicRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.DeleteTopicRequest =
  com.google.pubsub.v1.DeleteTopicRequestKt.Dsl._create(com.google.pubsub.v1.DeleteTopicRequest.newBuilder()).apply { block() }._build()
object DeleteTopicRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.DeleteTopicRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.DeleteTopicRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.DeleteTopicRequest = _builder.build()

    /**
     * <pre>
     * Required. Name of the topic to delete.
     * Format is `projects/{project}/topics/{topic}`.
     * </pre>
     *
     * <code>string topic = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var topic: kotlin.String
      @JvmName("getTopic")
      get() = _builder.getTopic()
      @JvmName("setTopic")
      set(value) {
        _builder.setTopic(value)
      }
    /**
     * <pre>
     * Required. Name of the topic to delete.
     * Format is `projects/{project}/topics/{topic}`.
     * </pre>
     *
     * <code>string topic = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearTopic() {
      _builder.clearTopic()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.DeleteTopicRequest.copy(block: com.google.pubsub.v1.DeleteTopicRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.DeleteTopicRequest =
  com.google.pubsub.v1.DeleteTopicRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
