//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun deleteSnapshotRequest(block: com.google.pubsub.v1.DeleteSnapshotRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.DeleteSnapshotRequest =
  com.google.pubsub.v1.DeleteSnapshotRequestKt.Dsl._create(com.google.pubsub.v1.DeleteSnapshotRequest.newBuilder()).apply { block() }._build()
object DeleteSnapshotRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.DeleteSnapshotRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.DeleteSnapshotRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.DeleteSnapshotRequest = _builder.build()

    /**
     * <pre>
     * Required. The name of the snapshot to delete.
     * Format is `projects/{project}/snapshots/{snap}`.
     * </pre>
     *
     * <code>string snapshot = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var snapshot: kotlin.String
      @JvmName("getSnapshot")
      get() = _builder.getSnapshot()
      @JvmName("setSnapshot")
      set(value) {
        _builder.setSnapshot(value)
      }
    /**
     * <pre>
     * Required. The name of the snapshot to delete.
     * Format is `projects/{project}/snapshots/{snap}`.
     * </pre>
     *
     * <code>string snapshot = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearSnapshot() {
      _builder.clearSnapshot()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.DeleteSnapshotRequest.copy(block: com.google.pubsub.v1.DeleteSnapshotRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.DeleteSnapshotRequest =
  com.google.pubsub.v1.DeleteSnapshotRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
