//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun listTopicSubscriptionsResponse(block: com.google.pubsub.v1.ListTopicSubscriptionsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListTopicSubscriptionsResponse =
  com.google.pubsub.v1.ListTopicSubscriptionsResponseKt.Dsl._create(com.google.pubsub.v1.ListTopicSubscriptionsResponse.newBuilder()).apply { block() }._build()
object ListTopicSubscriptionsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.ListTopicSubscriptionsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.ListTopicSubscriptionsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.ListTopicSubscriptionsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class SubscriptionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The names of subscriptions attached to the topic specified in the request.
     * </pre>
     *
     * <code>repeated string subscriptions = 1 [(.google.api.resource_reference) = { ... }</code>
     * @return A list containing the subscriptions.
     */
    val subscriptions: com.google.protobuf.kotlin.DslList<kotlin.String, SubscriptionsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSubscriptionsList()
      )
    /**
     * <pre>
     * The names of subscriptions attached to the topic specified in the request.
     * </pre>
     *
     * <code>repeated string subscriptions = 1 [(.google.api.resource_reference) = { ... }</code>
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSubscriptions")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, SubscriptionsProxy>.add(value: kotlin.String) {
      _builder.addSubscriptions(value)
    }
    /**
     * <pre>
     * The names of subscriptions attached to the topic specified in the request.
     * </pre>
     *
     * <code>repeated string subscriptions = 1 [(.google.api.resource_reference) = { ... }</code>
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSubscriptions")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SubscriptionsProxy>.plusAssign(value: kotlin.String) {
      _builder.addSubscriptions(value)
    }
    /**
     * <pre>
     * The names of subscriptions attached to the topic specified in the request.
     * </pre>
     *
     * <code>repeated string subscriptions = 1 [(.google.api.resource_reference) = { ... }</code>
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSubscriptions")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, SubscriptionsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSubscriptions(values)
    }
    /**
     * <pre>
     * The names of subscriptions attached to the topic specified in the request.
     * </pre>
     *
     * <code>repeated string subscriptions = 1 [(.google.api.resource_reference) = { ... }</code>
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSubscriptions")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SubscriptionsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSubscriptions(values)
    }
    /**
     * <pre>
     * The names of subscriptions attached to the topic specified in the request.
     * </pre>
     *
     * <code>repeated string subscriptions = 1 [(.google.api.resource_reference) = { ... }</code>
     * @param index The index to set the value at.
     * @param value The subscriptions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSubscriptions")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SubscriptionsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setSubscriptions(index, value)
    }/**
     * <pre>
     * The names of subscriptions attached to the topic specified in the request.
     * </pre>
     *
     * <code>repeated string subscriptions = 1 [(.google.api.resource_reference) = { ... }</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSubscriptions")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, SubscriptionsProxy>.clear() {
      _builder.clearSubscriptions()
    }
    /**
     * <pre>
     * If not empty, indicates that there may be more subscriptions that match
     * the request; this value should be passed in a new
     * `ListTopicSubscriptionsRequest` to get more subscriptions.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    var nextPageToken: kotlin.String
      @JvmName("getNextPageToken")
      get() = _builder.getNextPageToken()
      @JvmName("setNextPageToken")
      set(value) {
        _builder.setNextPageToken(value)
      }
    /**
     * <pre>
     * If not empty, indicates that there may be more subscriptions that match
     * the request; this value should be passed in a new
     * `ListTopicSubscriptionsRequest` to get more subscriptions.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    fun clearNextPageToken() {
      _builder.clearNextPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.ListTopicSubscriptionsResponse.copy(block: com.google.pubsub.v1.ListTopicSubscriptionsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListTopicSubscriptionsResponse =
  com.google.pubsub.v1.ListTopicSubscriptionsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
