//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun listSubscriptionsResponse(block: com.google.pubsub.v1.ListSubscriptionsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListSubscriptionsResponse =
  com.google.pubsub.v1.ListSubscriptionsResponseKt.Dsl._create(com.google.pubsub.v1.ListSubscriptionsResponse.newBuilder()).apply { block() }._build()
object ListSubscriptionsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.ListSubscriptionsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.ListSubscriptionsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.ListSubscriptionsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class SubscriptionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The subscriptions that match the request.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1;</code>
     */
     val subscriptions: com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Subscription, SubscriptionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSubscriptionsList()
      )
    /**
     * <pre>
     * The subscriptions that match the request.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1;</code>
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSubscriptions")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Subscription, SubscriptionsProxy>.add(value: com.google.pubsub.v1.Subscription) {
      _builder.addSubscriptions(value)
    }/**
     * <pre>
     * The subscriptions that match the request.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1;</code>
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSubscriptions")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Subscription, SubscriptionsProxy>.plusAssign(value: com.google.pubsub.v1.Subscription) {
      add(value)
    }/**
     * <pre>
     * The subscriptions that match the request.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1;</code>
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSubscriptions")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Subscription, SubscriptionsProxy>.addAll(values: kotlin.collections.Iterable<com.google.pubsub.v1.Subscription>) {
      _builder.addAllSubscriptions(values)
    }/**
     * <pre>
     * The subscriptions that match the request.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1;</code>
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSubscriptions")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Subscription, SubscriptionsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.pubsub.v1.Subscription>) {
      addAll(values)
    }/**
     * <pre>
     * The subscriptions that match the request.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1;</code>
     * @param index The index to set the value at.
     * @param value The subscriptions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSubscriptions")
    operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Subscription, SubscriptionsProxy>.set(index: kotlin.Int, value: com.google.pubsub.v1.Subscription) {
      _builder.setSubscriptions(index, value)
    }/**
     * <pre>
     * The subscriptions that match the request.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Subscription subscriptions = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSubscriptions")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Subscription, SubscriptionsProxy>.clear() {
      _builder.clearSubscriptions()
    }
    /**
     * <pre>
     * If not empty, indicates that there may be more subscriptions that match
     * the request; this value should be passed in a new
     * `ListSubscriptionsRequest` to get more subscriptions.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    var nextPageToken: kotlin.String
      @JvmName("getNextPageToken")
      get() = _builder.getNextPageToken()
      @JvmName("setNextPageToken")
      set(value) {
        _builder.setNextPageToken(value)
      }
    /**
     * <pre>
     * If not empty, indicates that there may be more subscriptions that match
     * the request; this value should be passed in a new
     * `ListSubscriptionsRequest` to get more subscriptions.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    fun clearNextPageToken() {
      _builder.clearNextPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.ListSubscriptionsResponse.copy(block: com.google.pubsub.v1.ListSubscriptionsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListSubscriptionsResponse =
  com.google.pubsub.v1.ListSubscriptionsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
