//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun listSubscriptionsRequest(block: com.google.pubsub.v1.ListSubscriptionsRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.ListSubscriptionsRequest =
  com.google.pubsub.v1.ListSubscriptionsRequestKt.Dsl._create(com.google.pubsub.v1.ListSubscriptionsRequest.newBuilder()).apply { block() }._build()
object ListSubscriptionsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.ListSubscriptionsRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.ListSubscriptionsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.ListSubscriptionsRequest = _builder.build()

    /**
     * <pre>
     * Required. The name of the project in which to list subscriptions.
     * Format is `projects/{project-id}`.
     * </pre>
     *
     * <code>string project = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var project: kotlin.String
      @JvmName("getProject")
      get() = _builder.getProject()
      @JvmName("setProject")
      set(value) {
        _builder.setProject(value)
      }
    /**
     * <pre>
     * Required. The name of the project in which to list subscriptions.
     * Format is `projects/{project-id}`.
     * </pre>
     *
     * <code>string project = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearProject() {
      _builder.clearProject()
    }

    /**
     * <pre>
     * Maximum number of subscriptions to return.
     * </pre>
     *
     * <code>int32 page_size = 2;</code>
     */
    var pageSize: kotlin.Int
      @JvmName("getPageSize")
      get() = _builder.getPageSize()
      @JvmName("setPageSize")
      set(value) {
        _builder.setPageSize(value)
      }
    /**
     * <pre>
     * Maximum number of subscriptions to return.
     * </pre>
     *
     * <code>int32 page_size = 2;</code>
     */
    fun clearPageSize() {
      _builder.clearPageSize()
    }

    /**
     * <pre>
     * The value returned by the last `ListSubscriptionsResponse`; indicates that
     * this is a continuation of a prior `ListSubscriptions` call, and that the
     * system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 3;</code>
     */
    var pageToken: kotlin.String
      @JvmName("getPageToken")
      get() = _builder.getPageToken()
      @JvmName("setPageToken")
      set(value) {
        _builder.setPageToken(value)
      }
    /**
     * <pre>
     * The value returned by the last `ListSubscriptionsResponse`; indicates that
     * this is a continuation of a prior `ListSubscriptions` call, and that the
     * system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 3;</code>
     */
    fun clearPageToken() {
      _builder.clearPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.ListSubscriptionsRequest.copy(block: com.google.pubsub.v1.ListSubscriptionsRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.ListSubscriptionsRequest =
  com.google.pubsub.v1.ListSubscriptionsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
