//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun listSnapshotsResponse(block: com.google.pubsub.v1.ListSnapshotsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListSnapshotsResponse =
  com.google.pubsub.v1.ListSnapshotsResponseKt.Dsl._create(com.google.pubsub.v1.ListSnapshotsResponse.newBuilder()).apply { block() }._build()
object ListSnapshotsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.ListSnapshotsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.ListSnapshotsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.ListSnapshotsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class SnapshotsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The resulting snapshots.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1;</code>
     */
     val snapshots: com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Snapshot, SnapshotsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSnapshotsList()
      )
    /**
     * <pre>
     * The resulting snapshots.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1;</code>
     * @param value The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSnapshots")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Snapshot, SnapshotsProxy>.add(value: com.google.pubsub.v1.Snapshot) {
      _builder.addSnapshots(value)
    }/**
     * <pre>
     * The resulting snapshots.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1;</code>
     * @param value The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSnapshots")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Snapshot, SnapshotsProxy>.plusAssign(value: com.google.pubsub.v1.Snapshot) {
      add(value)
    }/**
     * <pre>
     * The resulting snapshots.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1;</code>
     * @param values The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSnapshots")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Snapshot, SnapshotsProxy>.addAll(values: kotlin.collections.Iterable<com.google.pubsub.v1.Snapshot>) {
      _builder.addAllSnapshots(values)
    }/**
     * <pre>
     * The resulting snapshots.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1;</code>
     * @param values The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSnapshots")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Snapshot, SnapshotsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.pubsub.v1.Snapshot>) {
      addAll(values)
    }/**
     * <pre>
     * The resulting snapshots.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1;</code>
     * @param index The index to set the value at.
     * @param value The snapshots to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSnapshots")
    operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Snapshot, SnapshotsProxy>.set(index: kotlin.Int, value: com.google.pubsub.v1.Snapshot) {
      _builder.setSnapshots(index, value)
    }/**
     * <pre>
     * The resulting snapshots.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.Snapshot snapshots = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSnapshots")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.Snapshot, SnapshotsProxy>.clear() {
      _builder.clearSnapshots()
    }
    /**
     * <pre>
     * If not empty, indicates that there may be more snapshot that match the
     * request; this value should be passed in a new `ListSnapshotsRequest`.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    var nextPageToken: kotlin.String
      @JvmName("getNextPageToken")
      get() = _builder.getNextPageToken()
      @JvmName("setNextPageToken")
      set(value) {
        _builder.setNextPageToken(value)
      }
    /**
     * <pre>
     * If not empty, indicates that there may be more snapshot that match the
     * request; this value should be passed in a new `ListSnapshotsRequest`.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    fun clearNextPageToken() {
      _builder.clearNextPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.ListSnapshotsResponse.copy(block: com.google.pubsub.v1.ListSnapshotsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListSnapshotsResponse =
  com.google.pubsub.v1.ListSnapshotsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
