//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun listTopicSnapshotsResponse(block: com.google.pubsub.v1.ListTopicSnapshotsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListTopicSnapshotsResponse =
  com.google.pubsub.v1.ListTopicSnapshotsResponseKt.Dsl._create(com.google.pubsub.v1.ListTopicSnapshotsResponse.newBuilder()).apply { block() }._build()
object ListTopicSnapshotsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.ListTopicSnapshotsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.ListTopicSnapshotsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.ListTopicSnapshotsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class SnapshotsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The names of the snapshots that match the request.
     * </pre>
     *
     * <code>repeated string snapshots = 1;</code>
     * @return A list containing the snapshots.
     */
    val snapshots: com.google.protobuf.kotlin.DslList<kotlin.String, SnapshotsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSnapshotsList()
      )
    /**
     * <pre>
     * The names of the snapshots that match the request.
     * </pre>
     *
     * <code>repeated string snapshots = 1;</code>
     * @param value The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSnapshots")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, SnapshotsProxy>.add(value: kotlin.String) {
      _builder.addSnapshots(value)
    }
    /**
     * <pre>
     * The names of the snapshots that match the request.
     * </pre>
     *
     * <code>repeated string snapshots = 1;</code>
     * @param value The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSnapshots")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SnapshotsProxy>.plusAssign(value: kotlin.String) {
      _builder.addSnapshots(value)
    }
    /**
     * <pre>
     * The names of the snapshots that match the request.
     * </pre>
     *
     * <code>repeated string snapshots = 1;</code>
     * @param values The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSnapshots")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, SnapshotsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSnapshots(values)
    }
    /**
     * <pre>
     * The names of the snapshots that match the request.
     * </pre>
     *
     * <code>repeated string snapshots = 1;</code>
     * @param values The snapshots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSnapshots")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SnapshotsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSnapshots(values)
    }
    /**
     * <pre>
     * The names of the snapshots that match the request.
     * </pre>
     *
     * <code>repeated string snapshots = 1;</code>
     * @param index The index to set the value at.
     * @param value The snapshots to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSnapshots")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SnapshotsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setSnapshots(index, value)
    }/**
     * <pre>
     * The names of the snapshots that match the request.
     * </pre>
     *
     * <code>repeated string snapshots = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSnapshots")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, SnapshotsProxy>.clear() {
      _builder.clearSnapshots()
    }
    /**
     * <pre>
     * If not empty, indicates that there may be more snapshots that match
     * the request; this value should be passed in a new
     * `ListTopicSnapshotsRequest` to get more snapshots.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    var nextPageToken: kotlin.String
      @JvmName("getNextPageToken")
      get() = _builder.getNextPageToken()
      @JvmName("setNextPageToken")
      set(value) {
        _builder.setNextPageToken(value)
      }
    /**
     * <pre>
     * If not empty, indicates that there may be more snapshots that match
     * the request; this value should be passed in a new
     * `ListTopicSnapshotsRequest` to get more snapshots.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    fun clearNextPageToken() {
      _builder.clearNextPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.ListTopicSnapshotsResponse.copy(block: com.google.pubsub.v1.ListTopicSnapshotsResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.ListTopicSnapshotsResponse =
  com.google.pubsub.v1.ListTopicSnapshotsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
