//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun messageStoragePolicy(block: com.google.pubsub.v1.MessageStoragePolicyKt.Dsl.() -> Unit): com.google.pubsub.v1.MessageStoragePolicy =
  com.google.pubsub.v1.MessageStoragePolicyKt.Dsl._create(com.google.pubsub.v1.MessageStoragePolicy.newBuilder()).apply { block() }._build()
object MessageStoragePolicyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.MessageStoragePolicy.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.MessageStoragePolicy.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.MessageStoragePolicy = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class AllowedPersistenceRegionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A list of IDs of GCP regions where messages that are published to the topic
     * may be persisted in storage. Messages published by publishers running in
     * non-allowed GCP regions (or running outside of GCP altogether) will be
     * routed for storage in one of the allowed regions. An empty list means that
     * no regions are allowed, and is not a valid configuration.
     * </pre>
     *
     * <code>repeated string allowed_persistence_regions = 1;</code>
     * @return A list containing the allowedPersistenceRegions.
     */
    val allowedPersistenceRegions: com.google.protobuf.kotlin.DslList<kotlin.String, AllowedPersistenceRegionsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAllowedPersistenceRegionsList()
      )
    /**
     * <pre>
     * A list of IDs of GCP regions where messages that are published to the topic
     * may be persisted in storage. Messages published by publishers running in
     * non-allowed GCP regions (or running outside of GCP altogether) will be
     * routed for storage in one of the allowed regions. An empty list means that
     * no regions are allowed, and is not a valid configuration.
     * </pre>
     *
     * <code>repeated string allowed_persistence_regions = 1;</code>
     * @param value The allowedPersistenceRegions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllowedPersistenceRegions")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AllowedPersistenceRegionsProxy>.add(value: kotlin.String) {
      _builder.addAllowedPersistenceRegions(value)
    }
    /**
     * <pre>
     * A list of IDs of GCP regions where messages that are published to the topic
     * may be persisted in storage. Messages published by publishers running in
     * non-allowed GCP regions (or running outside of GCP altogether) will be
     * routed for storage in one of the allowed regions. An empty list means that
     * no regions are allowed, and is not a valid configuration.
     * </pre>
     *
     * <code>repeated string allowed_persistence_regions = 1;</code>
     * @param value The allowedPersistenceRegions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllowedPersistenceRegions")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AllowedPersistenceRegionsProxy>.plusAssign(value: kotlin.String) {
      _builder.addAllowedPersistenceRegions(value)
    }
    /**
     * <pre>
     * A list of IDs of GCP regions where messages that are published to the topic
     * may be persisted in storage. Messages published by publishers running in
     * non-allowed GCP regions (or running outside of GCP altogether) will be
     * routed for storage in one of the allowed regions. An empty list means that
     * no regions are allowed, and is not a valid configuration.
     * </pre>
     *
     * <code>repeated string allowed_persistence_regions = 1;</code>
     * @param values The allowedPersistenceRegions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAllowedPersistenceRegions")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AllowedPersistenceRegionsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAllowedPersistenceRegions(values)
    }
    /**
     * <pre>
     * A list of IDs of GCP regions where messages that are published to the topic
     * may be persisted in storage. Messages published by publishers running in
     * non-allowed GCP regions (or running outside of GCP altogether) will be
     * routed for storage in one of the allowed regions. An empty list means that
     * no regions are allowed, and is not a valid configuration.
     * </pre>
     *
     * <code>repeated string allowed_persistence_regions = 1;</code>
     * @param values The allowedPersistenceRegions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAllowedPersistenceRegions")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AllowedPersistenceRegionsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAllowedPersistenceRegions(values)
    }
    /**
     * <pre>
     * A list of IDs of GCP regions where messages that are published to the topic
     * may be persisted in storage. Messages published by publishers running in
     * non-allowed GCP regions (or running outside of GCP altogether) will be
     * routed for storage in one of the allowed regions. An empty list means that
     * no regions are allowed, and is not a valid configuration.
     * </pre>
     *
     * <code>repeated string allowed_persistence_regions = 1;</code>
     * @param index The index to set the value at.
     * @param value The allowedPersistenceRegions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAllowedPersistenceRegions")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AllowedPersistenceRegionsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setAllowedPersistenceRegions(index, value)
    }/**
     * <pre>
     * A list of IDs of GCP regions where messages that are published to the topic
     * may be persisted in storage. Messages published by publishers running in
     * non-allowed GCP regions (or running outside of GCP altogether) will be
     * routed for storage in one of the allowed regions. An empty list means that
     * no regions are allowed, and is not a valid configuration.
     * </pre>
     *
     * <code>repeated string allowed_persistence_regions = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAllowedPersistenceRegions")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AllowedPersistenceRegionsProxy>.clear() {
      _builder.clearAllowedPersistenceRegions()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.MessageStoragePolicy.copy(block: com.google.pubsub.v1.MessageStoragePolicyKt.Dsl.() -> Unit): com.google.pubsub.v1.MessageStoragePolicy =
  com.google.pubsub.v1.MessageStoragePolicyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
