//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun modifyAckDeadlineRequest(block: com.google.pubsub.v1.ModifyAckDeadlineRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.ModifyAckDeadlineRequest =
  com.google.pubsub.v1.ModifyAckDeadlineRequestKt.Dsl._create(com.google.pubsub.v1.ModifyAckDeadlineRequest.newBuilder()).apply { block() }._build()
object ModifyAckDeadlineRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.ModifyAckDeadlineRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.ModifyAckDeadlineRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.ModifyAckDeadlineRequest = _builder.build()

    /**
     * <pre>
     * Required. The name of the subscription.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var subscription: kotlin.String
      @JvmName("getSubscription")
      get() = _builder.getSubscription()
      @JvmName("setSubscription")
      set(value) {
        _builder.setSubscription(value)
      }
    /**
     * <pre>
     * Required. The name of the subscription.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearSubscription() {
      _builder.clearSubscription()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class AckIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Required. List of acknowledgment IDs.
     * </pre>
     *
     * <code>repeated string ack_ids = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return A list containing the ackIds.
     */
    val ackIds: com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAckIdsList()
      )
    /**
     * <pre>
     * Required. List of acknowledgment IDs.
     * </pre>
     *
     * <code>repeated string ack_ids = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAckIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.add(value: kotlin.String) {
      _builder.addAckIds(value)
    }
    /**
     * <pre>
     * Required. List of acknowledgment IDs.
     * </pre>
     *
     * <code>repeated string ack_ids = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAckIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.plusAssign(value: kotlin.String) {
      _builder.addAckIds(value)
    }
    /**
     * <pre>
     * Required. List of acknowledgment IDs.
     * </pre>
     *
     * <code>repeated string ack_ids = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param values The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAckIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAckIds(values)
    }
    /**
     * <pre>
     * Required. List of acknowledgment IDs.
     * </pre>
     *
     * <code>repeated string ack_ids = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param values The ackIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAckIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAckIds(values)
    }
    /**
     * <pre>
     * Required. List of acknowledgment IDs.
     * </pre>
     *
     * <code>repeated string ack_ids = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param index The index to set the value at.
     * @param value The ackIds to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAckIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setAckIds(index, value)
    }/**
     * <pre>
     * Required. List of acknowledgment IDs.
     * </pre>
     *
     * <code>repeated string ack_ids = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAckIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, AckIdsProxy>.clear() {
      _builder.clearAckIds()
    }
    /**
     * <pre>
     * Required. The new ack deadline with respect to the time this request was
     * sent to the Pub/Sub system. For example, if the value is 10, the new ack
     * deadline will expire 10 seconds after the `ModifyAckDeadline` call was
     * made. Specifying zero might immediately make the message available for
     * delivery to another subscriber client. This typically results in an
     * increase in the rate of message redeliveries (that is, duplicates).
     * The minimum deadline you can specify is 0 seconds.
     * The maximum deadline you can specify is 600 seconds (10 minutes).
     * </pre>
     *
     * <code>int32 ack_deadline_seconds = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    var ackDeadlineSeconds: kotlin.Int
      @JvmName("getAckDeadlineSeconds")
      get() = _builder.getAckDeadlineSeconds()
      @JvmName("setAckDeadlineSeconds")
      set(value) {
        _builder.setAckDeadlineSeconds(value)
      }
    /**
     * <pre>
     * Required. The new ack deadline with respect to the time this request was
     * sent to the Pub/Sub system. For example, if the value is 10, the new ack
     * deadline will expire 10 seconds after the `ModifyAckDeadline` call was
     * made. Specifying zero might immediately make the message available for
     * delivery to another subscriber client. This typically results in an
     * increase in the rate of message redeliveries (that is, duplicates).
     * The minimum deadline you can specify is 0 seconds.
     * The maximum deadline you can specify is 600 seconds (10 minutes).
     * </pre>
     *
     * <code>int32 ack_deadline_seconds = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    fun clearAckDeadlineSeconds() {
      _builder.clearAckDeadlineSeconds()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.ModifyAckDeadlineRequest.copy(block: com.google.pubsub.v1.ModifyAckDeadlineRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.ModifyAckDeadlineRequest =
  com.google.pubsub.v1.ModifyAckDeadlineRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
