//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun modifyPushConfigRequest(block: com.google.pubsub.v1.ModifyPushConfigRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.ModifyPushConfigRequest =
  com.google.pubsub.v1.ModifyPushConfigRequestKt.Dsl._create(com.google.pubsub.v1.ModifyPushConfigRequest.newBuilder()).apply { block() }._build()
object ModifyPushConfigRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.ModifyPushConfigRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.ModifyPushConfigRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.ModifyPushConfigRequest = _builder.build()

    /**
     * <pre>
     * Required. The name of the subscription.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var subscription: kotlin.String
      @JvmName("getSubscription")
      get() = _builder.getSubscription()
      @JvmName("setSubscription")
      set(value) {
        _builder.setSubscription(value)
      }
    /**
     * <pre>
     * Required. The name of the subscription.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearSubscription() {
      _builder.clearSubscription()
    }

    /**
     * <pre>
     * Required. The push configuration for future deliveries.
     * An empty `pushConfig` indicates that the Pub/Sub system should
     * stop pushing messages from the given subscription and allow
     * messages to be pulled and acknowledged - effectively pausing
     * the subscription if `Pull` or `StreamingPull` is not called.
     * </pre>
     *
     * <code>.google.pubsub.v1.PushConfig push_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    var pushConfig: com.google.pubsub.v1.PushConfig
      @JvmName("getPushConfig")
      get() = _builder.getPushConfig()
      @JvmName("setPushConfig")
      set(value) {
        _builder.setPushConfig(value)
      }
    /**
     * <pre>
     * Required. The push configuration for future deliveries.
     * An empty `pushConfig` indicates that the Pub/Sub system should
     * stop pushing messages from the given subscription and allow
     * messages to be pulled and acknowledged - effectively pausing
     * the subscription if `Pull` or `StreamingPull` is not called.
     * </pre>
     *
     * <code>.google.pubsub.v1.PushConfig push_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    fun clearPushConfig() {
      _builder.clearPushConfig()
    }
    /**
     * <pre>
     * Required. The push configuration for future deliveries.
     * An empty `pushConfig` indicates that the Pub/Sub system should
     * stop pushing messages from the given subscription and allow
     * messages to be pulled and acknowledged - effectively pausing
     * the subscription if `Pull` or `StreamingPull` is not called.
     * </pre>
     *
     * <code>.google.pubsub.v1.PushConfig push_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the pushConfig field is set.
     */
    fun hasPushConfig(): kotlin.Boolean {
      return _builder.hasPushConfig()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.ModifyPushConfigRequest.copy(block: com.google.pubsub.v1.ModifyPushConfigRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.ModifyPushConfigRequest =
  com.google.pubsub.v1.ModifyPushConfigRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
