//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun publishRequest(block: com.google.pubsub.v1.PublishRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.PublishRequest =
  com.google.pubsub.v1.PublishRequestKt.Dsl._create(com.google.pubsub.v1.PublishRequest.newBuilder()).apply { block() }._build()
object PublishRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.PublishRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.PublishRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.PublishRequest = _builder.build()

    /**
     * <pre>
     * Required. The messages in the request will be published on this topic.
     * Format is `projects/{project}/topics/{topic}`.
     * </pre>
     *
     * <code>string topic = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var topic: kotlin.String
      @JvmName("getTopic")
      get() = _builder.getTopic()
      @JvmName("setTopic")
      set(value) {
        _builder.setTopic(value)
      }
    /**
     * <pre>
     * Required. The messages in the request will be published on this topic.
     * Format is `projects/{project}/topics/{topic}`.
     * </pre>
     *
     * <code>string topic = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearTopic() {
      _builder.clearTopic()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class MessagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Required. The messages to publish.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.PubsubMessage messages = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
     val messages: com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.PubsubMessage, MessagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMessagesList()
      )
    /**
     * <pre>
     * Required. The messages to publish.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.PubsubMessage messages = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMessages")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.PubsubMessage, MessagesProxy>.add(value: com.google.pubsub.v1.PubsubMessage) {
      _builder.addMessages(value)
    }/**
     * <pre>
     * Required. The messages to publish.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.PubsubMessage messages = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMessages")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.PubsubMessage, MessagesProxy>.plusAssign(value: com.google.pubsub.v1.PubsubMessage) {
      add(value)
    }/**
     * <pre>
     * Required. The messages to publish.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.PubsubMessage messages = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMessages")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.PubsubMessage, MessagesProxy>.addAll(values: kotlin.collections.Iterable<com.google.pubsub.v1.PubsubMessage>) {
      _builder.addAllMessages(values)
    }/**
     * <pre>
     * Required. The messages to publish.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.PubsubMessage messages = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMessages")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.PubsubMessage, MessagesProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.pubsub.v1.PubsubMessage>) {
      addAll(values)
    }/**
     * <pre>
     * Required. The messages to publish.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.PubsubMessage messages = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param index The index to set the value at.
     * @param value The messages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMessages")
    operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.PubsubMessage, MessagesProxy>.set(index: kotlin.Int, value: com.google.pubsub.v1.PubsubMessage) {
      _builder.setMessages(index, value)
    }/**
     * <pre>
     * Required. The messages to publish.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.PubsubMessage messages = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMessages")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.PubsubMessage, MessagesProxy>.clear() {
      _builder.clearMessages()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.PublishRequest.copy(block: com.google.pubsub.v1.PublishRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.PublishRequest =
  com.google.pubsub.v1.PublishRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
