//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun publishResponse(block: com.google.pubsub.v1.PublishResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.PublishResponse =
  com.google.pubsub.v1.PublishResponseKt.Dsl._create(com.google.pubsub.v1.PublishResponse.newBuilder()).apply { block() }._build()
object PublishResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.PublishResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.PublishResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.PublishResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class MessageIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The server-assigned ID of each published message, in the same order as
     * the messages in the request. IDs are guaranteed to be unique within
     * the topic.
     * </pre>
     *
     * <code>repeated string message_ids = 1;</code>
     * @return A list containing the messageIds.
     */
    val messageIds: com.google.protobuf.kotlin.DslList<kotlin.String, MessageIdsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMessageIdsList()
      )
    /**
     * <pre>
     * The server-assigned ID of each published message, in the same order as
     * the messages in the request. IDs are guaranteed to be unique within
     * the topic.
     * </pre>
     *
     * <code>repeated string message_ids = 1;</code>
     * @param value The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMessageIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, MessageIdsProxy>.add(value: kotlin.String) {
      _builder.addMessageIds(value)
    }
    /**
     * <pre>
     * The server-assigned ID of each published message, in the same order as
     * the messages in the request. IDs are guaranteed to be unique within
     * the topic.
     * </pre>
     *
     * <code>repeated string message_ids = 1;</code>
     * @param value The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMessageIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MessageIdsProxy>.plusAssign(value: kotlin.String) {
      _builder.addMessageIds(value)
    }
    /**
     * <pre>
     * The server-assigned ID of each published message, in the same order as
     * the messages in the request. IDs are guaranteed to be unique within
     * the topic.
     * </pre>
     *
     * <code>repeated string message_ids = 1;</code>
     * @param values The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMessageIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, MessageIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllMessageIds(values)
    }
    /**
     * <pre>
     * The server-assigned ID of each published message, in the same order as
     * the messages in the request. IDs are guaranteed to be unique within
     * the topic.
     * </pre>
     *
     * <code>repeated string message_ids = 1;</code>
     * @param values The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMessageIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MessageIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllMessageIds(values)
    }
    /**
     * <pre>
     * The server-assigned ID of each published message, in the same order as
     * the messages in the request. IDs are guaranteed to be unique within
     * the topic.
     * </pre>
     *
     * <code>repeated string message_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The messageIds to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMessageIds")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MessageIdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setMessageIds(index, value)
    }/**
     * <pre>
     * The server-assigned ID of each published message, in the same order as
     * the messages in the request. IDs are guaranteed to be unique within
     * the topic.
     * </pre>
     *
     * <code>repeated string message_ids = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMessageIds")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, MessageIdsProxy>.clear() {
      _builder.clearMessageIds()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.PublishResponse.copy(block: com.google.pubsub.v1.PublishResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.PublishResponse =
  com.google.pubsub.v1.PublishResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
