//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun pullResponse(block: com.google.pubsub.v1.PullResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.PullResponse =
  com.google.pubsub.v1.PullResponseKt.Dsl._create(com.google.pubsub.v1.PullResponse.newBuilder()).apply { block() }._build()
object PullResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.PullResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.PullResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.PullResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ReceivedMessagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Received Pub/Sub messages. The list will be empty if there are no more
     * messages available in the backlog. For JSON, the response can be entirely
     * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
     * even if there are more messages available in the backlog.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1;</code>
     */
     val receivedMessages: com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.ReceivedMessage, ReceivedMessagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getReceivedMessagesList()
      )
    /**
     * <pre>
     * Received Pub/Sub messages. The list will be empty if there are no more
     * messages available in the backlog. For JSON, the response can be entirely
     * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
     * even if there are more messages available in the backlog.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1;</code>
     * @param value The receivedMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addReceivedMessages")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.ReceivedMessage, ReceivedMessagesProxy>.add(value: com.google.pubsub.v1.ReceivedMessage) {
      _builder.addReceivedMessages(value)
    }/**
     * <pre>
     * Received Pub/Sub messages. The list will be empty if there are no more
     * messages available in the backlog. For JSON, the response can be entirely
     * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
     * even if there are more messages available in the backlog.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1;</code>
     * @param value The receivedMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignReceivedMessages")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.ReceivedMessage, ReceivedMessagesProxy>.plusAssign(value: com.google.pubsub.v1.ReceivedMessage) {
      add(value)
    }/**
     * <pre>
     * Received Pub/Sub messages. The list will be empty if there are no more
     * messages available in the backlog. For JSON, the response can be entirely
     * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
     * even if there are more messages available in the backlog.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1;</code>
     * @param values The receivedMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllReceivedMessages")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.ReceivedMessage, ReceivedMessagesProxy>.addAll(values: kotlin.collections.Iterable<com.google.pubsub.v1.ReceivedMessage>) {
      _builder.addAllReceivedMessages(values)
    }/**
     * <pre>
     * Received Pub/Sub messages. The list will be empty if there are no more
     * messages available in the backlog. For JSON, the response can be entirely
     * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
     * even if there are more messages available in the backlog.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1;</code>
     * @param values The receivedMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllReceivedMessages")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.ReceivedMessage, ReceivedMessagesProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.pubsub.v1.ReceivedMessage>) {
      addAll(values)
    }/**
     * <pre>
     * Received Pub/Sub messages. The list will be empty if there are no more
     * messages available in the backlog. For JSON, the response can be entirely
     * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
     * even if there are more messages available in the backlog.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1;</code>
     * @param index The index to set the value at.
     * @param value The receivedMessages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setReceivedMessages")
    operator fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.ReceivedMessage, ReceivedMessagesProxy>.set(index: kotlin.Int, value: com.google.pubsub.v1.ReceivedMessage) {
      _builder.setReceivedMessages(index, value)
    }/**
     * <pre>
     * Received Pub/Sub messages. The list will be empty if there are no more
     * messages available in the backlog. For JSON, the response can be entirely
     * empty. The Pub/Sub system may return fewer than the `maxMessages` requested
     * even if there are more messages available in the backlog.
     * </pre>
     *
     * <code>repeated .google.pubsub.v1.ReceivedMessage received_messages = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearReceivedMessages")
    fun com.google.protobuf.kotlin.DslList<com.google.pubsub.v1.ReceivedMessage, ReceivedMessagesProxy>.clear() {
      _builder.clearReceivedMessages()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.PullResponse.copy(block: com.google.pubsub.v1.PullResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.PullResponse =
  com.google.pubsub.v1.PullResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
