//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun pullRequest(block: com.google.pubsub.v1.PullRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.PullRequest =
  com.google.pubsub.v1.PullRequestKt.Dsl._create(com.google.pubsub.v1.PullRequest.newBuilder()).apply { block() }._build()
object PullRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.PullRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.PullRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.PullRequest = _builder.build()

    /**
     * <pre>
     * Required. The subscription from which messages should be pulled.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    var subscription: kotlin.String
      @JvmName("getSubscription")
      get() = _builder.getSubscription()
      @JvmName("setSubscription")
      set(value) {
        _builder.setSubscription(value)
      }
    /**
     * <pre>
     * Required. The subscription from which messages should be pulled.
     * Format is `projects/{project}/subscriptions/{sub}`.
     * </pre>
     *
     * <code>string subscription = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     */
    fun clearSubscription() {
      _builder.clearSubscription()
    }

    /**
     * <pre>
     * Optional. If this field set to true, the system will respond immediately
     * even if it there are no messages available to return in the `Pull`
     * response. Otherwise, the system may wait (for a bounded amount of time)
     * until at least one message is available, rather than returning no messages.
     * Warning: setting this field to `true` is discouraged because it adversely
     * impacts the performance of `Pull` operations. We recommend that users do
     * not set this field.
     * </pre>
     *
     * <code>bool return_immediately = 2 [deprecated = true, (.google.api.field_behavior) = OPTIONAL];</code>
     */
    @kotlin.Deprecated(message = "Field returnImmediately is deprecated") var returnImmediately: kotlin.Boolean
      @JvmName("getReturnImmediately")
      get() = _builder.getReturnImmediately()
      @JvmName("setReturnImmediately")
      set(value) {
        _builder.setReturnImmediately(value)
      }
    /**
     * <pre>
     * Optional. If this field set to true, the system will respond immediately
     * even if it there are no messages available to return in the `Pull`
     * response. Otherwise, the system may wait (for a bounded amount of time)
     * until at least one message is available, rather than returning no messages.
     * Warning: setting this field to `true` is discouraged because it adversely
     * impacts the performance of `Pull` operations. We recommend that users do
     * not set this field.
     * </pre>
     *
     * <code>bool return_immediately = 2 [deprecated = true, (.google.api.field_behavior) = OPTIONAL];</code>
     */
    fun clearReturnImmediately() {
      _builder.clearReturnImmediately()
    }

    /**
     * <pre>
     * Required. The maximum number of messages to return for this request. Must
     * be a positive integer. The Pub/Sub system may return fewer than the number
     * specified.
     * </pre>
     *
     * <code>int32 max_messages = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    var maxMessages: kotlin.Int
      @JvmName("getMaxMessages")
      get() = _builder.getMaxMessages()
      @JvmName("setMaxMessages")
      set(value) {
        _builder.setMaxMessages(value)
      }
    /**
     * <pre>
     * Required. The maximum number of messages to return for this request. Must
     * be a positive integer. The Pub/Sub system may return fewer than the number
     * specified.
     * </pre>
     *
     * <code>int32 max_messages = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    fun clearMaxMessages() {
      _builder.clearMaxMessages()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.PullRequest.copy(block: com.google.pubsub.v1.PullRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.PullRequest =
  com.google.pubsub.v1.PullRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
