//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun seekResponse(block: com.google.pubsub.v1.SeekResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.SeekResponse =
  com.google.pubsub.v1.SeekResponseKt.Dsl._create(com.google.pubsub.v1.SeekResponse.newBuilder()).apply { block() }._build()
object SeekResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.SeekResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.SeekResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.SeekResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.SeekResponse.copy(block: com.google.pubsub.v1.SeekResponseKt.Dsl.() -> Unit): com.google.pubsub.v1.SeekResponse =
  com.google.pubsub.v1.SeekResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
