//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun updateTopicRequest(block: com.google.pubsub.v1.UpdateTopicRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.UpdateTopicRequest =
  com.google.pubsub.v1.UpdateTopicRequestKt.Dsl._create(com.google.pubsub.v1.UpdateTopicRequest.newBuilder()).apply { block() }._build()
object UpdateTopicRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.UpdateTopicRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.UpdateTopicRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.UpdateTopicRequest = _builder.build()

    /**
     * <pre>
     * Required. The updated topic object.
     * </pre>
     *
     * <code>.google.pubsub.v1.Topic topic = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    var topic: com.google.pubsub.v1.Topic
      @JvmName("getTopic")
      get() = _builder.getTopic()
      @JvmName("setTopic")
      set(value) {
        _builder.setTopic(value)
      }
    /**
     * <pre>
     * Required. The updated topic object.
     * </pre>
     *
     * <code>.google.pubsub.v1.Topic topic = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    fun clearTopic() {
      _builder.clearTopic()
    }
    /**
     * <pre>
     * Required. The updated topic object.
     * </pre>
     *
     * <code>.google.pubsub.v1.Topic topic = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the topic field is set.
     */
    fun hasTopic(): kotlin.Boolean {
      return _builder.hasTopic()
    }

    /**
     * <pre>
     * Required. Indicates which fields in the provided topic to update. Must be
     * specified and non-empty. Note that if `update_mask` contains
     * "message_storage_policy" but the `message_storage_policy` is not set in
     * the `topic` provided above, then the updated value is determined by the
     * policy configured at the project or organization level.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    var updateMask: com.google.protobuf.FieldMask
      @JvmName("getUpdateMask")
      get() = _builder.getUpdateMask()
      @JvmName("setUpdateMask")
      set(value) {
        _builder.setUpdateMask(value)
      }
    /**
     * <pre>
     * Required. Indicates which fields in the provided topic to update. Must be
     * specified and non-empty. Note that if `update_mask` contains
     * "message_storage_policy" but the `message_storage_policy` is not set in
     * the `topic` provided above, then the updated value is determined by the
     * policy configured at the project or organization level.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    fun clearUpdateMask() {
      _builder.clearUpdateMask()
    }
    /**
     * <pre>
     * Required. Indicates which fields in the provided topic to update. Must be
     * specified and non-empty. Note that if `update_mask` contains
     * "message_storage_policy" but the `message_storage_policy` is not set in
     * the `topic` provided above, then the updated value is determined by the
     * policy configured at the project or organization level.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the updateMask field is set.
     */
    fun hasUpdateMask(): kotlin.Boolean {
      return _builder.hasUpdateMask()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.UpdateTopicRequest.copy(block: com.google.pubsub.v1.UpdateTopicRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.UpdateTopicRequest =
  com.google.pubsub.v1.UpdateTopicRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
