//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/pubsub/v1/pubsub.proto

package com.google.pubsub.v1;

@kotlin.jvm.JvmSynthetic
inline fun updateSubscriptionRequest(block: com.google.pubsub.v1.UpdateSubscriptionRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.UpdateSubscriptionRequest =
  com.google.pubsub.v1.UpdateSubscriptionRequestKt.Dsl._create(com.google.pubsub.v1.UpdateSubscriptionRequest.newBuilder()).apply { block() }._build()
object UpdateSubscriptionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.pubsub.v1.UpdateSubscriptionRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.pubsub.v1.UpdateSubscriptionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.pubsub.v1.UpdateSubscriptionRequest = _builder.build()

    /**
     * <pre>
     * Required. The updated subscription object.
     * </pre>
     *
     * <code>.google.pubsub.v1.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    var subscription: com.google.pubsub.v1.Subscription
      @JvmName("getSubscription")
      get() = _builder.getSubscription()
      @JvmName("setSubscription")
      set(value) {
        _builder.setSubscription(value)
      }
    /**
     * <pre>
     * Required. The updated subscription object.
     * </pre>
     *
     * <code>.google.pubsub.v1.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    fun clearSubscription() {
      _builder.clearSubscription()
    }
    /**
     * <pre>
     * Required. The updated subscription object.
     * </pre>
     *
     * <code>.google.pubsub.v1.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the subscription field is set.
     */
    fun hasSubscription(): kotlin.Boolean {
      return _builder.hasSubscription()
    }

    /**
     * <pre>
     * Required. Indicates which fields in the provided subscription to update.
     * Must be specified and non-empty.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    var updateMask: com.google.protobuf.FieldMask
      @JvmName("getUpdateMask")
      get() = _builder.getUpdateMask()
      @JvmName("setUpdateMask")
      set(value) {
        _builder.setUpdateMask(value)
      }
    /**
     * <pre>
     * Required. Indicates which fields in the provided subscription to update.
     * Must be specified and non-empty.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    fun clearUpdateMask() {
      _builder.clearUpdateMask()
    }
    /**
     * <pre>
     * Required. Indicates which fields in the provided subscription to update.
     * Must be specified and non-empty.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the updateMask field is set.
     */
    fun hasUpdateMask(): kotlin.Boolean {
      return _builder.hasUpdateMask()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.pubsub.v1.UpdateSubscriptionRequest.copy(block: com.google.pubsub.v1.UpdateSubscriptionRequestKt.Dsl.() -> Unit): com.google.pubsub.v1.UpdateSubscriptionRequest =
  com.google.pubsub.v1.UpdateSubscriptionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
