{
  "formatVersion": "1.1",
  "component": {
    "group": "io.grpc",
    "module": "grpc-kotlin",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sjo5soc3cjb3xd44bey5ong4ua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-kotlin-0.1.jar",
          "url": "grpc-kotlin-0.1.jar",
          "size": 21166132,
          "sha512": "5157a68edf7c06113908d714795eab50b992aeed38710f510456fcc311131ee49ed1502d5d11e5ea15267d87cfa14a2ca06a1839bc693b1765eeec155edc81e9",
          "sha256": "97dbcd090c68794372a3405d9257c491c90c2709ebd0d627a24b3f509bf70de8",
          "sha1": "a8b0a8e0d100fa6b9913cb54a06c4e5137e28809",
          "md5": "af0184561f4ba742f6870d72c2d8b4f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-kotlin-0.1.jar",
          "url": "grpc-kotlin-0.1.jar",
          "size": 21166132,
          "sha512": "5157a68edf7c06113908d714795eab50b992aeed38710f510456fcc311131ee49ed1502d5d11e5ea15267d87cfa14a2ca06a1839bc693b1765eeec155edc81e9",
          "sha256": "97dbcd090c68794372a3405d9257c491c90c2709ebd0d627a24b3f509bf70de8",
          "sha1": "a8b0a8e0d100fa6b9913cb54a06c4e5137e28809",
          "md5": "af0184561f4ba742f6870d72c2d8b4f5"
        }
      ]
    }
  ]
}
