import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://code.google.com/appengine/ */
    const val appengine: String = "com.google.appengine:appengine:" + Versions.appengine

    /**
     * https://github.com/GoogleCloudPlatform/app-gradle-plugin */
    const val appengine_gradle_plugin: String = "com.google.cloud.tools:appengine-gradle-plugin:" +
            Versions.appengine_gradle_plugin

    const val google_cloud_logging_logback: String =
            "com.google.cloud:google-cloud-logging-logback:" + Versions.google_cloud_logging_logback

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/ktorio/ktor */
    const val ktor_html_builder: String = "io.ktor:ktor-html-builder:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor */
    const val ktor_server_servlet: String = "io.ktor:ktor-server-servlet:" + Versions.io_ktor

    /**
     * https://kotlinlang.org/ */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin
}
