name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Install ktlint
      run: |
        curl -sSLO https://github.com/shyiko/ktlint/releases/download/0.48.2/ktlint
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv ktlint "${GITHUB_WORKSPACE}/bin/ktlint"
        chmod +x "${GITHUB_WORKSPACE}/bin/ktlint"
    - name: Run ktlint
      run: |
        "${GITHUB_WORKSPACE}/bin/ktlint" "**/*".kt '!**/build/generated/**' --version
        "${GITHUB_WORKSPACE}/bin/ktlint" "**/*".kt '!**/build/generated/**' -l=info
